### ISSUE TITLE
Header with blue background jumps every update time

### ISSUE THREAD

**Issue by KorneevVitaly** [gsass1/NTop#30]
When ntop is working, the header disapeares and reappeares each update time (regardless if it's in cmd.exe or ConEmu), which looks like everything jumps up and down. Here the screenshots:
![3](https://user-images.githubusercontent.com/47393025/85881771-d446eb00-b7e6-11ea-8066-69f1841f0848.png)
![2](https://user-images.githubusercontent.com/47393025/85881778-d7da7200-b7e6-11ea-8e6e-a135ce34fe99.png)

**Comment by gsass1** [comment]
What kind of terminal is that?

**Comment by KorneevVitaly** [comment]
I'm using ConEmu. Tried open ntop in regular cmd.exe and it has the same behaviour. Also, my system is Windows 8.1.

**Comment by KorneevVitaly** [comment]
> What kind of terminal is that?
I'm using ConEmu. 

Tried open ntop in regular cmd.exe and it has the same behaviour. Also, my system is Windows 8.1.

**Comment by gsass1** [comment]
Well this statement https://github.com/gsass1/NTop/blob/master/ntop.c#L1767 (`DISABLE_NEWLINE_AUTO_RETURN`) is what should prevent the buffer from scrolling on the last line. IDK why that doesn't work on Windows 8.1 :/

**Comment by KorneevVitaly** [comment]
I tieed build it with build.bat and I've got an error with "error C2275: WORD:invalid use of this type"
![Screenshot_1](https://user-images.githubusercontent.com/47393025/85944153-59441880-b93d-11ea-8001-9f048404bdcc.png)

And in \minwindef.h(159) it's:
typedef unsigned short      WORD;

**Comment by Krikonildo** [comment]
Work as intended with Windows 10 command line.
Same problem with Windows 7 command line.
Maybe a command line option to disable the header ?

**Comment by Alex313031** [comment]
Can confirm on windows x64 7, server 2011, 8, 8.1. Havent tested in ten but probably works as Krikonildo said. I love all the "tops" for Unix/Linux i.e. top, htop, nvtop, atop. There is no other program like this and I really like it just disappointing me with the jittering up and down it can make it hard to read. Also verified on 32 bit windows 7 in command.com.

**Comment by Alex313031** [comment]
Update @Krikonildo @KorneevVitaly  @gsass1 WORKS as intended IF you set compatibility mode to Windows XP SP3 in the executables properties. This works for 7, and 8.1 but strangely not 8. Of course my 8 is in a VM whereas 7 and 8.1 are real machines but idk if that makes a difference. Compiling works with VS 2017 AND 2015 with platform update on win 7. Same issues and same resolution no matter what is used to compile.

**Comment by Alex313031** [comment]
I have it in a directory in my path, and if I launch it from cmd (not double clicking ntop), this only resolves it IF you keep the default ~80X24 Prompt size

**Comment by greatquux** [comment]
Actually, while playing with your workaround, I found another one which doesn't require changing terminal size or compatibility options - just press / as if you were going to do a search, but then don't do anything, and the display calms down and keeps updating. Annoying for sure, in that if you want to re-sort you have to backspace first, but it does work. This display has been steady for many minutes now:

[cid:4b465bf5ac4a95e53eb9ba801b982911baf6b944.camel@papersolve.com-0]



--
Michael Russo | Systems Engineer | PaperSolve, Inc.
office (718) 477 8906 | direct (332) 228 1817


Randomly generated quote of the last 5 minutes:

Jim, this is Janelle. I'm flying tonight, so I can't make our date, and
I gotta find a safe place for Daffy. He loves you, Jim!  It's only two
days, and you'll see. Great Danes are no problem!

              -- "The Rockford Files"

**Comment by Krikonildo** [comment]
@Alex313031
Didn't work for me ( Windows 7 x64 ).
Neither compatibility mode or cmd.
Works without DISABLE_NEWLINE_AUTO_RETURN ( Linux / MinGW ).
Even on Vista x86 recompiling with GetTickCount.

**Comment by gsass1** [comment]
Hello

I just pushed another commit that maybe fixes this. I would be grateful if someone could just compile the latest commit and tell me if it works since I don't have a Windows 7 VM atm.

**Comment by greatquux** [comment]
I compiled the latest version and it seems to work great on my Windows Server 2012 R2 now where it was previously jumping around (unless I pressed '/').

**Comment by Alex313031** [comment]
@greatquux @Krikonildo The / works better because you can resize, also works on win 8. I had an SSD fail and had to recover alot of files and reinstall win 7 on a new ssd. Don't have alot of stuff set up including VS, so is there a way you could share your latest compiled version so I can try. Also cudos to @gsass1 for bein so quick about everything.

**Comment by Alex313031** [comment]
@Krikonildo Your'e still using Vista in 2020!! JK I use win xp and win 98 for old stuff, and have VMs of vista. Anyway, VS 2013 and higher requires >Win 7 and 2015 and higher requires > Win 7 with 2013 Platform Update [https://www.microsoft.com/en-us/download/details.aspx?id=36805](url) So how in the world did you compile it on that.

**Comment by greatquux** [comment]
@Alex313031 I will send you a link to the last compiled version I have, it was while doing some troubleshooting for the issue 34 so it leaves some stuff in the background when you quit and if it cannot find a username it displays it as "default" but otherwise works fine.

**Comment by Alex313031** [comment]
@greatquux Thnx

**Comment by Alex313031** [comment]
@greatquux Crashes on launch on Win 7 sp1 ultimate x64

**Comment by greatquux** [comment]
Unfortunately I don't have that exact version of OS to test against, but I am able to run the same binary on a Windows Server 2008 R2 SP1 (which is always x64):

[cid:0370012875f03f4369b66480bd538cc9189ab898.camel@papersolve.com-0]



--

Michael Russo | Systems Engineer | PaperSolve, Inc.
office (718) 477 8906 | direct (332) 228 1817

Your random quote for today:
There's no easy quick way out, we're gonna have to live through our
whole lives, win, lose, or draw.
                -- Walt Kelly


-----Original Message-----

**Comment by iqlat** [comment]
Same issue, title flickering on latest build (from scoop/git repo); tested as standalone .exe and in Cmder; on Windows 7 x64 Pro; it stops only when window looses focus => **[gif_link](https://i.imgur.com/Wc0r6SS.gif)**; the workaround with "/" crashes app.

**Comment by iqlat** [comment]
**upd:** nov, 2021 -> this issue seems to be fixed in the latest source code; you can compile it by your own or download the compiled one from [**google drive**](https://drive.google.com/file/d/1CO8OKj3g-A574x1KUG6yWKx1Tu1BNiTw/view?usp=sharing).
